
# The run will be created at: <root_dir>/confluence_<run_name>/
root_dir: "/nas/cee-water/cjgleason/ted/confluence/"
run_name: "end_to_end"

roi_file: "/nas/cee-water/cjgleason/ted/confluence/test_roi.json"

# priors_bind_dir: "/nas/cee-water/cjgleason/ted/confluence/_empty_v4/empty_mnt/input/sos"
# priors_copy_dir: "/nas/cee-water/cjgleason/ted/confluence/_empty_v4/empty_mnt/input/sos"
priors_zenodo_doi: "10.5281/zenodo.20541765"

# sword_bind_dir: "/nas/cee-water/cjgleason/ted/confluence/_empty_v4/empty_mnt/input/sword"
# sword_copy_dir: "/nas/cee-water/cjgleason/ted/confluence/_empty_v4/empty_mnt/input/sword"
sword_zenodo_doi: "10.5281/zenodo.15299138"

# svs_copy_dir: "/nas/cee-water/cjgleason/ted/confluence/_empty_v4/empty_mnt/validation"
svs_repo_filename: "SVS_v1_0_1.nc"

default_github_username: "SWOT-Confluence"
default_repository_branch: "main" # Can also be per-module in `repo_branches`
default_image_release_tag: 4.0.0

clone_repos: True
build_modules: True
submit_driver: True

modules_to_run:
  - "expanded_setfinder"
  - "expanded_combine_data"
  - "input"
  - "non_expanded_setfinder"
  - "non_expanded_combine_data"
  - "prediagnostics"
  - "metroman"
  - "metroman_consolidation"
  - "unconstrained_momma"
  - "busboi"
  - "hivdi"
  # - "sic4dvar"
  - "consensus"
  - "validation"
  - "output"

repo_branches:
  setfinder: "tedlanghorst:main"
  busboi: "BUSBOI_main"
  validation: "post_UAT"

hpc:
  partition: "ceewater_cjgleason-cpu"
  account: "pi_cjgleason_umass_edu"
  time: "1-00:00:00"
  batch_size: 1000
  concurrent_jobs: 400
  reach_chunks: 20


# Really a module argument but so many of them use it we spec it once.
# Must always be the same for each module too.
sword_version: "17"


module_templates:
  expanded_setfinder:
    time: "06:00:00"
    mem: "4G"
    j2_file: "modules/setfinder.sh.j2"
    module_args: 
      reach_file: "-r reaches_of_interest.json"
      expanded: True

  non_expanded_setfinder:
    time: "06:00:00"
    mem: "4G"
    j2_file: "modules/setfinder.sh.j2"
    module_args:
      reach_file: "-r expanded_reaches_of_interest.json"
      expanded: False

  expanded_combine_data:
    time: "06:00:00"
    mem: "4G"
    j2_file: "modules/combine_data.sh.j2"
    module_args:
      expanded: True

  non_expanded_combine_data:
    time: "06:00:00"
    mem: "4G"
    j2_file: "modules/combine_data.sh.j2"
    module_args:
      expanded: False

  input:
    time: "24:00:00"
    mem: "4G"
    j2_file: "modules/input.sh.j2"
    module_args:
      collection: "SWOT_L2_HR_RiverSP_D"
      time_range: "&start_time=2020-09-01T00:00:00Z&end_time=2026-12-30T00:00:00Z&"
      continue_downloads: True

  prediagnostics:
    time: "06:00:00"
    mem: "4G"
    j2_file: "modules/prediagnostics.sh.j2"

  hivdi:
    time: "06:00:00"
    mem: "4G"
    j2_file: "modules/hivdi.sh.j2"

  busboi:
    time: "06:00:00"
    mem: "4G"
    j2_file: "modules/busboi.sh.j2"

  sic4dvar:
    time: "06:00:00"
    mem: "4G"
    j2_file: "modules/sic4dvar.sh.j2"
    module_args:
      config_file: "sic4dvar_param_confluence.ini"

  metroman:
    time: "06:00:00"
    mem: "4G"
    j2_file: "modules/metroman.sh.j2"

  metroman_consolidation:
    time: "06:00:00"
    mem: "4G"
    j2_file: "modules/metroman_consolidation.sh.j2"

  unconstrained_momma:
    time: "06:00:00"
    mem: "4G"
    j2_file: "modules/momma.sh.j2"
    module_args:
      m_parameter: 3
      constrained: False

  constrained_momma:
    time: "06:00:00"
    mem: "4G"
    j2_file: "modules/momma.sh.j2"
    module_args:
      m_parameter: 3
      constrained: True

  sad:
    time: "06:00:00"
    mem: "4G"
    j2_file: "modules/sad.sh.j2"

  moi:
    time: "00:30:00"
    mem: "2G"
    j2_file: "modules/moi.sh.j2"
    module_args:
      basin_type: "unconstrained"

  consensus:
    time: "06:00:00"
    mem: "4G"
    j2_file: "modules/consensus.sh.j2"

  unconstrained_offline:
    time: "06:00:00"
    mem: "4G"
    j2_file: "modules/offline.sh.j2"

  validation:
    time: "06:00:00"
    mem: "4G"
    j2_file: "modules/validation.sh.j2"

  output:
    time: "05:00:00"
    mem: "8G"
    j2_file: "modules/output.sh.j2"
    module_args: 
      groups: "input prediagnostics momma metroman sic4dvar hivdi busboi consensus swot validation"
