root_dir: "/nas/cee-water/cjgleason/ted/confluence/"
empty_dir: "/nas/cee-water/cjgleason/ted/confluence/_empty_v4"
roi_file: "/nas/cee-water/cjgleason/ted/confluence/test_roi.json"

run_name: "end_to_end"
github_username: "SWOT-Confluence"
default_branch: "main" # Can also be per-module in `module_branches`
image_release_tag: 4.0.0

# Good for testing but this is dangerous for experiments if you forget to change `root_dir` and or `run_name`.
overwrite_run: False
clone_repos: False
rebuild_modules: False

# This limits the number of jobs that the slurm driver will create for the per-reach jobs
max_reaches: 10

modules_to_run:
  # - "expanded_setfinder"
  # - "expanded_combine_data"
  # - "input"
  # - "non_expanded_setfinder"
  # - "non_expanded_combine_data"
  # - "prediagnostics"
  # # - "priors"
  - "metroman"
  - "metroman_consolidation"
  - "unconstrained_momma"
  - "busboi"
  - "hivdi"
  - "sic4dvar"
  - "consensus"
  # # # - "moi"
  - "validation"
  - "output"

# images_to_build:
#   - "setfinder"
#   - "combine_data"
#   - "input"
#   - "prediagnostics"
#   - "priors"
#   - "metroman"
#   - "metroman_consolidation"
#   - "momma"
  # - "busboi"
#   - "hivdi"
#   - "sad"
#   - "sic4dvar"
#   - "consensus"
#   - "moi"
#   - "offline"
#   - "validation"
#   - "output"


### 
# advanced github
###
# Any branch can also define alternate owner of repo as "owner:branch"
# Ex: 'tedlanghorst:main'

# You can optionally define specific branches for specific modules.
# Default branch will be used for any that are not specified. 
# module_branches:
#   setfinder: "main"
#   combine_data: "tedlanghorst:dev"
#   # etc... 
####

module_branches:
  busboi: "BUSBOI_main"


hpc:
  partition: "ceewater_cjgleason-cpu"
  account: "pi_cjgleason_umass_edu"
  time: "7-00:00:00"
  batch_size: 1000
  concurrent_jobs: 400
  reach_chunks: 20


# Really a module argument but so many of them use it
# Must always be the same for each module too.
sword_version: "17"

module_template_args:
  expanded_setfinder:
    time: "06:00:00"
    mem: "4G"
    extra_args: "-r reaches_of_interest.json"
    expanded: True
    template: "modules/setfinder.sh.j2"
  non_expanded_setfinder:
    time: "06:00:00"
    mem: "4G"
    expanded: False
    template: "modules/setfinder.sh.j2"
  expanded_combine_data:
    time: "06:00:00"
    mem: "4G"
    expanded: True
    template: "modules/combine_data.sh.j2"
  non_expanded_combine_data:
    time: "06:00:00"
    mem: "4G"
    expanded: False
    template: "modules/combine_data.sh.j2"
  input:
    time: "24:00:00"
    mem: "4G"
    collection: "SWOT_L2_HR_RiverSP_D"
    time_range: "&start_time=2020-09-01T00:00:00Z&end_time=2026-12-30T00:00:00Z&"
    continue_downloads: True
    template: "modules/input.sh.j2"
  prediagnostics:
    time: "06:00:00"
    mem: "4G"
    template: "modules/prediagnostics.sh.j2"
  hivdi:
    time: "06:00:00"
    mem: "4G"
    template: "modules/hivdi.sh.j2"
  busboi:
    time: "06:00:00"
    mem: "4G"
    template: "modules/busboi.sh.j2"
  sic4dvar:
    time: "06:00:00"
    mem: "4G"
    config_file: "sic4dvar_param_confluence.ini"
    template: "modules/sic4dvar.sh.j2"
  metroman:
    time: "06:00:00"
    mem: "4G"
    template: "modules/metroman.sh.j2"
  metroman_consolidation:
    time: "06:00:00"
    mem: "4G"
    template: "modules/metroman_consolidation.sh.j2"
  unconstrained_momma:
    time: "06:00:00"
    mem: "4G"
    m_parameter: 3
    constrained: False
    template: "modules/momma.sh.j2"
  constrained_momma:
    time: "06:00:00"
    mem: "4G"
    m_parameter: 3
    constrained: True
    template: "modules/momma.sh.j2"
  sad:
    time: "06:00:00"
    mem: "4G"
    template: "modules/sad.sh.j2"
  moi:
    time: "00:30:00"
    mem: "2G"
    basin_type: "unconstrained"
    template: "modules/moi.sh.j2"
  consensus:
    time: "06:00:00"
    mem: "4G"
    template: "modules/consensus.sh.j2"
  unconstrained_offline:
    time: "06:00:00"
    mem: "4G"
    template: "modules/offline.sh.j2"
  validation:
    time: "06:00:00"
    mem: "4G"
    template: "modules/validation.sh.j2"
  output:
    time: "05:00:00"
    mem: "8G"
    groups: "input prediagnostics momma metroman sic4dvar hivdi busboi consensus swot validation"
    template: "modules/output.sh.j2"